In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import HashingVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import *
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import *
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import GridSearchCV




In [2]:
cd "C:\Users\Theo\Downloads"

C:\Users\Theo\Downloads


In [45]:
data= pd.DataFrame.from_csv('ML_HW1_data.csv')

C:\Users\Theo\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: from_csv is deprecated. Please use read_csv(...) instead. Note that some of the default arguments are different, so please refer to the documentation for from_csv when changing your function calls
  """Entry point for launching an IPython kernel.


In [19]:
data.head()

instructions optimizer compiler
0  push push push test je mov mov mov call mov mo...         L      gcc
1                        xor cmp mov seta cmovae ret         H      gcc
2  mov add mov call mov movzx mov call test je mo...         L      gcc
3  push mov push mov sub test mov jne test jne te...         H      gcc
4  push sub mov mov mov mov mov mov mov mov mov m...         L      gcc

In [4]:
vectorizer = HashingVectorizer(ngram_range=(5,7),analyzer='word') # multivariate


In [33]:
#vectorizer = HashingVectorizer(ngram_range=(3,9),analyzer='word') # multivariate


In [5]:
X_all = vectorizer.fit_transform(data.instructions)
y_all = data.compiler


In [38]:
X_all.shape

(30000, 1048576)

In [8]:
#from sklearn import random_projection

In [9]:
#transformer = random_projection.SparseRandomProjection()

In [10]:
#X_new=transformer.fit_transform(X_all)

In [11]:
#_new.shape

(30000, 8836)

### try a logistic regression for multiclass classification

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X_all, y_all, 
          test_size=0.2, random_state=1453)

In [7]:
model= LogisticRegression(multi_class='multinomial',solver='newton-cg').fit(X_train,y_train)

In [36]:
y_pred = model.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[1623  233  103]
 [ 151 1701  144]
 [ 153  176 1716]]
              precision    recall  f1-score   support

       clang       0.84      0.83      0.84      1959
         gcc       0.81      0.85      0.83      1996
         icc       0.87      0.84      0.86      2045

   micro avg       0.84      0.84      0.84      6000
   macro avg       0.84      0.84      0.84      6000
weighted avg       0.84      0.84      0.84      6000



In [37]:
cv = ShuffleSplit(n_splits=5, test_size=0.333, random_state=120)
scores = cross_val_score(model, X_all, y_all, cv=cv)
print(scores)
print("Accuracy: %0.3f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
  

[0.82802803 0.83503504 0.83513514 0.83023023 0.83363363]
Accuracy: 0.832 (+/- 0.01)


### Try a Decision Tree Classifier

In [10]:
model0 = DecisionTreeClassifier().fit(X_train,y_train)

In [11]:
y_pred = model0.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[1379  358  222]
 [ 247 1536  213]
 [ 285  336 1424]]
              precision    recall  f1-score   support

       clang       0.72      0.70      0.71      1959
         gcc       0.69      0.77      0.73      1996
         icc       0.77      0.70      0.73      2045

   micro avg       0.72      0.72      0.72      6000
   macro avg       0.73      0.72      0.72      6000
weighted avg       0.73      0.72      0.72      6000



In [21]:
cv = ShuffleSplit(n_splits=5, test_size=0.333, random_state=120)
scores = cross_val_score(model0, X_all, y_all, cv=cv)
print(scores)
print("Accuracy: %0.3f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

[0.71051051 0.71261261 0.71191191 0.70740741 0.71531532]
Accuracy: 0.712 (+/- 0.01)


### Create a linear svm classification, one over all

In [18]:
model1=svm.SVC(gamma='scale',kernel='linear',cache_size=4000,decision_function_shape='ovo').fit(X_train,y_train)

In [19]:
y_pred = model1.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[1652  213   94]
 [ 155 1710  131]
 [ 147  147 1751]]
              precision    recall  f1-score   support

       clang       0.85      0.84      0.84      1959
         gcc       0.83      0.86      0.84      1996
         icc       0.89      0.86      0.87      2045

   micro avg       0.85      0.85      0.85      6000
   macro avg       0.85      0.85      0.85      6000
weighted avg       0.85      0.85      0.85      6000



In [38]:
model2 = svm.LinearSVC().fit(X_train,y_train)

In [39]:
y_pred = model2.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred,labels=['clang','gcc','icc']))

[[1691  179   89]
 [ 130 1755  111]
 [ 112  114 1819]]
              precision    recall  f1-score   support

       clang       0.87      0.86      0.87      1959
         gcc       0.86      0.88      0.87      1996
         icc       0.90      0.89      0.90      2045

   micro avg       0.88      0.88      0.88      6000
   macro avg       0.88      0.88      0.88      6000
weighted avg       0.88      0.88      0.88      6000



### try a random forest classifier,compiled of 100 decision trees

In [21]:
model3=RandomForestClassifier(n_estimators=100,n_jobs=4).fit(X_train,y_train)

In [22]:
y_pred = model3.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred,labels=['clang','gcc','icc']))

[[1644  244   71]
 [ 189 1688  119]
 [ 250  185 1610]]
              precision    recall  f1-score   support

       clang       0.79      0.84      0.81      1959
         gcc       0.80      0.85      0.82      1996
         icc       0.89      0.79      0.84      2045

   micro avg       0.82      0.82      0.82      6000
   macro avg       0.83      0.82      0.82      6000
weighted avg       0.83      0.82      0.82      6000



In [23]:
cv = ShuffleSplit(n_splits=5, test_size=0.333, random_state=120)
scores = cross_val_score(model3, X_all, y_all, cv=cv)
print(scores)
print("Accuracy: %0.3f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
  

[0.81281281 0.82162162 0.81851852 0.81621622 0.81371371]
Accuracy: 0.817 (+/- 0.01)


### naive bayes classifier

In [46]:
vectorizer = HashingVectorizer(ngram_range=(5,7),analyzer='word',non_negative=True) # multivariate


In [47]:
X_all = vectorizer.fit_transform(data.instructions)
y_all = data.compiler


C:\Users\Theo\Anaconda3\lib\site-packages\sklearn\feature_extraction\hashing.py:102: DeprecationWarning: the option non_negative=True has been deprecated in 0.19 and will be removed in version 0.21.
  " in version 0.21.", DeprecationWarning)
C:\Users\Theo\Anaconda3\lib\site-packages\sklearn\feature_extraction\hashing.py:102: DeprecationWarning: the option non_negative=True has been deprecated in 0.19 and will be removed in version 0.21.
  " in version 0.21.", DeprecationWarning)


In [48]:
X_train, X_test, y_train, y_test = train_test_split(X_all, y_all, 
          test_size=0.2, random_state=1453)

In [18]:
model4 = MultinomialNB(fit_prior=True).fit(X_train,y_train)

In [19]:
y_pred = model4.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[1641  188  130]
 [ 239 1572  185]
 [ 188  102 1755]]
              precision    recall  f1-score   support

       clang       0.79      0.84      0.81      1959
         gcc       0.84      0.79      0.81      1996
         icc       0.85      0.86      0.85      2045

   micro avg       0.83      0.83      0.83      6000
   macro avg       0.83      0.83      0.83      6000
weighted avg       0.83      0.83      0.83      6000



In [20]:
cv = ShuffleSplit(n_splits=5, test_size=0.333, random_state=120)
scores = cross_val_score(model4, X_all, y_all, cv=cv)
print(scores)
print("Accuracy: %0.3f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
  

[0.81861862 0.82412412 0.82672673 0.82692693 0.82562563]
Accuracy: 0.824 (+/- 0.01)


### Perform a grid search on naive bayes hyperparameters

In [28]:
grid_values = {'fit_prior': ['True', 'False'],'alpha':[0.001,0.01,0.1,1,5,10]}
grid_acc = GridSearchCV(model4, param_grid = grid_values,scoring = 'accuracy',cv=5,iid=False,n_jobs=4).fit(X_all,y_all)

In [29]:
for i in range(0,len(grid_acc.cv_results_['params'])):
    print("[%2d] params: %s  \tscore: %.3f +/- %.3f" %(i,
        grid_acc.cv_results_['params'][i],
        grid_acc.cv_results_['mean_test_score'][i],
        grid_acc.cv_results_['std_test_score'][i] ))

a = np.argmax(grid_acc.cv_results_['mean_test_score'])
bestparams = grid_acc.cv_results_['params'][a]
bestscore = grid_acc.cv_results_['mean_test_score'][a]

print("Best configuration [%d] %r  %.3f" %(a,bestparams,bestscore))

[ 0] params: {'alpha': 0.001, 'fit_prior': 'True'}  	score: 0.882 +/- 0.005
[ 1] params: {'alpha': 0.001, 'fit_prior': 'False'}  	score: 0.882 +/- 0.005
[ 2] params: {'alpha': 0.01, 'fit_prior': 'True'}  	score: 0.884 +/- 0.004
[ 3] params: {'alpha': 0.01, 'fit_prior': 'False'}  	score: 0.884 +/- 0.004
[ 4] params: {'alpha': 0.1, 'fit_prior': 'True'}  	score: 0.872 +/- 0.005
[ 5] params: {'alpha': 0.1, 'fit_prior': 'False'}  	score: 0.872 +/- 0.005
[ 6] params: {'alpha': 1, 'fit_prior': 'True'}  	score: 0.830 +/- 0.003
[ 7] params: {'alpha': 1, 'fit_prior': 'False'}  	score: 0.830 +/- 0.003
[ 8] params: {'alpha': 5, 'fit_prior': 'True'}  	score: 0.769 +/- 0.003
[ 9] params: {'alpha': 5, 'fit_prior': 'False'}  	score: 0.769 +/- 0.003
[10] params: {'alpha': 10, 'fit_prior': 'True'}  	score: 0.732 +/- 0.003
[11] params: {'alpha': 10, 'fit_prior': 'False'}  	score: 0.732 +/- 0.003
Best configuration [2] {'alpha': 0.01, 'fit_prior': 'True'}  0.884


In [49]:
model5 = MultinomialNB(fit_prior=True,alpha=0.01).fit(X_train,y_train)

In [50]:
y_pred = model5.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[1716  167   76]
 [ 147 1758   91]
 [ 124  107 1814]]
              precision    recall  f1-score   support

       clang       0.86      0.88      0.87      1959
         gcc       0.87      0.88      0.87      1996
         icc       0.92      0.89      0.90      2045

   micro avg       0.88      0.88      0.88      6000
   macro avg       0.88      0.88      0.88      6000
weighted avg       0.88      0.88      0.88      6000



### Predict the optimizer for the blind test set

In [36]:
def create_table_2(name_of_file):
    dictionary=dict()
    with open(name_of_file,"r") as data:
        for number,line in enumerate(data):
            instructions=[]
            instr= line.strip('{"instructions": [').split("],")[0].replace('"','')
            for i in range(len(instr.split(', '))):
                try:
                    instructions.append(instr.split(', ')[i].split()[0])

                except:
                    print('error or instance  '+str(i)+ 'and number  '+str(number)+ 'with text:   '+ str(instr.split(', ')[i].split()))

           

            dictionary[number]=[' '.join(instructions).strip(']}')]
    return dictionary


In [37]:
data_test= pd.DataFrame.from_dict(create_table_2("test_dataset_blind.jsonl"),orient='index',columns=['instructions'])

In [51]:
data_test.head()

instructions
0  push push push push push push sub mov mov mov ...
1  mov mov mov xor call nop mov call nop test jne...
2                                mov neg shr mov ret
3  push push mov push push mov sub mov call test ...
4  est jne mov lea mov mov mov mov call mov mov m...

In [52]:
X_all_test = vectorizer.fit_transform(data_test.instructions) # the vectorizer of naive bayes with non negative values


C:\Users\Theo\Anaconda3\lib\site-packages\sklearn\feature_extraction\hashing.py:102: DeprecationWarning: the option non_negative=True has been deprecated in 0.19 and will be removed in version 0.21.
  " in version 0.21.", DeprecationWarning)
C:\Users\Theo\Anaconda3\lib\site-packages\sklearn\feature_extraction\hashing.py:102: DeprecationWarning: the option non_negative=True has been deprecated in 0.19 and will be removed in version 0.21.
  " in version 0.21.", DeprecationWarning)


In [53]:
compiler_predictions = model5.predict(X_all_test)


In [56]:
sum(compiler_predictions=='clang')

982

In [57]:
sum(compiler_predictions=='gcc')

1014

In [58]:
sum(compiler_predictions=='icc')

1004

In [54]:
compiler_predictions

array(['gcc', 'gcc', 'clang', ..., 'gcc', 'clang', 'clang'], dtype='<U5')

In [55]:
np.savetxt("ML_HW1_compilers_predictions.csv", compiler_predictions,fmt='%s')